apiVersion: extensions/v1beta1
kind: Deployment                                          # 1
metadata:
  name: bp-frontend
spec:
  replicas: 2                                             # 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate                                   # 3
    rollingUpdate:
      maxUnavailable: 1                                   # 4
      maxSurge: 1                                         # 5
  template:
    metadata:
      labels:
        app: bp-frontend                                  # 6
    spec:
      containers:
        - image: benya/bp-frontend
          imagePullPolicy: Always                         # 7
          name: bp-frontend
          ports:
            - containerPort: 80
