apiVersion: v1
kind: Service
metadata:
  name: bp-springhibernate-lb
spec:
  type: LoadBalancer
  ports:
    - port: 70
      protocol: TCP
      targetPort: 8080
  selector:
    app: bp-springhibernate
